services:
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ADDRESS=http://node1:8000
      - SEED_NODES=http://node2:8001,http://node3:8002
      - PORT=8000
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ..:/app

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ADDRESS=http://node2:8001
      - SEED_NODES=http://node1:8000,http://node3:8002
      - PORT=8001
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    volumes:
      - ..:/app

  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ADDRESS=http://node3:8002
      - SEED_NODES=http://node1:8000,http://node2:8001
      - PORT=8002
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
    volumes:
      - ..:/app
